allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true

peerDependencyRules:
  allowedVersions:
    "@vercel/analytics>vue-router": "^5.2.0"
    "@vercel/speed-insights>vue-router": "^5.2.0"
    "unctx>oxc-parser": "^0.139.0"
    "unctx>unplugin": "^2.3.11"
onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
patchedDependencies:
  nuxt-og-image@6.7.4: patches/nuxt-og-image@6.7.4.patch
